"""AI content plan generator — narrative-core + skeleton + batch generator.

Architecture (cost-optimized):

  1. Narrative core & strategy  — generated ONCE per profile (gpt-5.4),
     cached in the profile row for 30 days. Free on subsequent plans.
     (see app.services.content_narrative)

  2. Deterministic skeleton      — pure Python. Defines cadence (daily
     stories + reels every 2 days), hunt-stage per slot, and reserved
     Meepo-bot CTA slots for the funnel goal.
     (see app.services.content_skeleton)

  3. Batch post generator        — ONE gpt-5.4-mini call that receives
     the narrative core + the skeleton table, and returns ready-to-publish
     text + voiceover scripts for every slot.

Net token cost per plan:
  * first plan for a profile  = 1 gpt-5.4 call (core) + 1 gpt-5.4-mini call (posts)
  * every subsequent plan     = 1 gpt-5.4-mini call (posts) — core is cached
"""
import json
import logging
import asyncio

import httpx
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.models import (
    CompetitorPost,
    CompetitorSource,
    ContentPlan,
    ContentPlanItem,
    ContentProfile,
)
from app.services.content_narrative import ensure_narrative_core
from app.services.content_skeleton import (
    Slot,
    build_skeleton,
    skeleton_to_prompt_table,
)

logger = logging.getLogger(__name__)

_DEFAULT_OPENAI_URL = "https://api.openai.com/v1/chat/completions"
# Posts are generated by the cheap model — the skeleton already guarantees structure.
_MODEL_POSTS = "gpt-5.4-mini"
# Fallback model for when the primary route (Cloudflare Gateway / gpt-5.4-mini) is unavailable.
_FALLBACK_MODEL = "gpt-4o-mini"
_TIMEOUT = 180
_MAX_GPT_RETRIES = 3



def _get_openai_url() -> str:
    if settings.OPENAI_BASE_URL:
        base = settings.OPENAI_BASE_URL.rstrip("/")
        return f"{base}/chat/completions"
    return _DEFAULT_OPENAI_URL


async def _call_gpt(
    messages: list[dict],
    temperature: float = 0.7,
    max_completion_tokens: int = 8000,
    model: str = _MODEL_POSTS,
) -> str:
    """Call OpenAI API and return content string."""
    headers = {
        "Authorization": f"Bearer {settings.OPENAI_API_KEY}",
        "Content-Type": "application/json",
    }
    if settings.CF_AIG_TOKEN:
        headers["cf-aig-authorization"] = f"Bearer {settings.CF_AIG_TOKEN}"
    payload = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "max_completion_tokens": max_completion_tokens,
    }

    last_exc = None
    for attempt in range(1, _MAX_GPT_RETRIES + 1):
        try:
            async with httpx.AsyncClient(timeout=_TIMEOUT) as client:
                resp = await client.post(_get_openai_url(), json=payload, headers=headers)
                resp.raise_for_status()
                data = resp.json()
                return data["choices"][0]["message"]["content"]
        except (httpx.ReadTimeout, httpx.ReadError) as e:
            last_exc = e
            if attempt >= _MAX_GPT_RETRIES:
                break
            delay = float(attempt)
            logger.warning(
                "GPT request timeout/read error (attempt %d/%d), retry in %.1fs",
                attempt,
                _MAX_GPT_RETRIES,
                delay,
            )
            await asyncio.sleep(delay)
        except httpx.HTTPStatusError as e:
            status = e.response.status_code if e.response else None
            retriable = status in (429, 500, 502, 503, 504)
            if retriable and attempt < _MAX_GPT_RETRIES:
                delay = float(attempt)
                logger.warning(
                    "GPT HTTP %s (attempt %d/%d), retry in %.1fs",
                    status,
                    attempt,
                    _MAX_GPT_RETRIES,
                    delay,
                )
                await asyncio.sleep(delay)
                continue
            raise

    if last_exc:
        # Try a direct-OpenAI fallback using the fallback model if primary kept failing
        # and we were going through a gateway (CF AI Gateway). Otherwise re-raise.
        if settings.OPENAI_BASE_URL and model != _FALLBACK_MODEL:
            logger.warning(
                "GPT primary route (%s via gateway) exhausted retries, falling back to %s direct",
                model,
                _FALLBACK_MODEL,
            )
            try:
                fb_headers = {
                    "Authorization": f"Bearer {settings.OPENAI_API_KEY}",
                    "Content-Type": "application/json",
                }
                fb_payload = dict(payload, model=_FALLBACK_MODEL)
                async with httpx.AsyncClient(timeout=_TIMEOUT) as client:
                    resp = await client.post(_DEFAULT_OPENAI_URL, json=fb_payload, headers=fb_headers)
                    resp.raise_for_status()
                    return resp.json()["choices"][0]["message"]["content"]
            except Exception as fb_err:
                logger.error("GPT fallback also failed: %s", fb_err)
        raise last_exc
    raise RuntimeError("GPT call failed")


async def _gather_competitor_data(profile: ContentProfile, db: AsyncSession) -> str:
    """Collect cached competitor posts for the user's profile.

    Priority:
      1. User-specific competitors (CompetitorSource linked to profile)
      2. Global FitLine reference database (top posts by engagement)
    """
    sources = await db.execute(
        select(CompetitorSource).where(
            CompetitorSource.profile_id == profile.id,
            CompetitorSource.is_active == True,
        )
    )
    sources = sources.scalars().all()

    sections = []

    # ── User-specific competitors ──
    for src in sources:
        posts = await db.execute(
            select(CompetitorPost)
            .where(
                CompetitorPost.platform == src.platform,
                CompetitorPost.channel_username == src.channel_username,
            )
            .order_by(CompetitorPost.posted_at.desc())
            .limit(15)
        )
        posts = posts.scalars().all()
        if not posts:
            continue

        post_texts = []
        for p in posts:
            meta = []
            if p.views:
                meta.append(f"👁 {p.views}")
            if p.reactions:
                meta.append(f"❤️ {p.reactions}")
            meta_str = f" ({', '.join(meta)})" if meta else ""
            post_texts.append(f"- {p.text[:300]}{meta_str}")

        sections.append(
            f"### {src.platform.upper()} @{src.channel_username}\n"
            + "\n".join(post_texts[:10])
        )

    # ── Global FitLine reference (fallback or supplement) ──
    if not sections:
        ref_posts = await db.execute(
            select(CompetitorPost)
            .where(CompetitorPost.platform == "instagram")
            .order_by(CompetitorPost.reactions.desc().nullslast())
            .limit(25)
        )
        ref_posts = ref_posts.scalars().all()

        if ref_posts:
            ref_texts = []
            for p in ref_posts:
                meta = []
                if p.reactions:
                    meta.append(f"❤️ {p.reactions}")
                meta_str = f" ({', '.join(meta)})" if meta else ""
                ref_texts.append(f"- @{p.channel_username}: {p.text[:300]}{meta_str}")

            sections.append(
                "### РЕФЕРЕНС: Топ-посты успешных FitLine-продавцов (по вовлечению)\n"
                + "\n".join(ref_texts)
            )

    if not sections:
        return "Конкурентов не добавлено. Генерируй на основе ниши и ЦА."

    return "\n\n".join(sections)


def _build_batch_posts_prompt(
    *,
    profile: ContentProfile,
    platform_name: str,
    narrative_text: str,
    strategy: dict,
    skeleton_table: str,
    competitor_data: str,
    meepo_link: str | None,
) -> str:
    """Compose the single prompt for the batch post generator.

    The prompt keeps GPT in a tight, structural role: fill the given slots.
    All strategic thinking has already been done by the narrative-core step
    (cached) and the Python skeleton (free), so we can safely use a cheap model.
    """
    meepo_hint = (
        f"Meepo-бот deeplink для слотов с meepo_cta=YES: {meepo_link}"
        if meepo_link
        else "Meepo-бот deeplink не задан — в слотах с meepo_cta=YES используй обобщённый CTA «напиши в личного AI-ассистента»."
    )
    strategy_compact = json.dumps(strategy, ensure_ascii=False)[:1500]

    return f"""Ты — SMM-копирайтер. Твоя задача — ЗАПОЛНИТЬ готовый скелет контент-плана.
Всю стратегию (боли, углы, тональность) уже определил стратег — ты её получаешь и НЕ переизобретаешь.

## Профиль автора
- Ниша: {profile.niche}
- Платформа: {platform_name}
- Тон: {profile.tone}
- Целевая аудитория: {profile.target_audience or 'не указана'}

{narrative_text}

## Стратегия (кеш)
{strategy_compact}

## Референсы конкурентов (только для вдохновения, не копируй)
{competitor_data[:2000]}

## Контекст бренда FitLine (используется только в слотах hunt_stage=product)
- Premium БАДы PM-International, технология NTC (усвоение до 5x)
- Оптимальный Сет: Activize (энергия утром), Restorate (восстановление вечером), Basics (ЖКТ/иммунитет)
- НИКОГДА: «купи», «скидка», прямая цена

## Воронка в Meepo-бота
{meepo_hint}
Слоты с meepo_cta=YES — это most_aware стадия. Цель: подписчик должен захотеть написать боту.
Формула для таких слотов: личный мини-кейс (как бот помог автору или знакомой) → прямой CTA.

## СКЕЛЕТ (таблица слотов, заполни каждый)
{skeleton_table}

## ПРАВИЛА
1. Для каждой строки скелета сгенерируй ОДИН элемент результата с тем же day и type.
2. Строго держись hunt_stage: это определяет, о чём пост и как он заканчивается.
3. Первая строка текста — сильный крючок (hook), использующий паттерны из narrative core.
4. Используй signature_metaphors автора — повторяющиеся образы создают узнаваемость.
5. Длины:
   - сторис: текст 60-180 символов, скрипт 40-100 слов (10-20 сек речи)
   - рилс:   текст 100-300 символов, скрипт 150-300 слов (30-60 сек речи)
6. Для Instagram — 5-8 релевантных хештегов в поле hashtags. Для Telegram — hashtags=null.
7. Поле script обязательно для сторис и рилс (разговорный русский, без эмодзи, без markdown, без хештегов).
   Для постов/каруселей script="".
8. Никаких placeholder'ов, никаких «[вставьте сюда ...]», никакого lorem ipsum.

## ФОРМАТ ОТВЕТА (строго JSON-массив, без markdown, без комментариев)
[
  {{
    "day": <int>,
    "type": "сторис|рилс|пост|карусель",
    "topic": "краткая тема (до 80 символов)",
    "text": "готовый текст для публикации",
    "hashtags": "#тег1 #тег2" или null,
    "time": "HH:MM",
    "script": "текст для озвучки или пустая строка"
  }}
]

Сгенерируй ровно столько элементов, сколько строк в скелете. Не пропускай, не добавляй."""


async def generate_content_plan(
    user_id: int,
    platform: str,
    period_days: int,
    db: AsyncSession,
) -> ContentPlan:
    """Generate a content plan synchronously (kept for backward compat/tests).

    Returns created ContentPlan with items. Status = 'ready' or 'error'.
    """
    # Load profile
    result = await db.execute(
        select(ContentProfile).where(ContentProfile.user_id == user_id)
    )
    profile = result.scalar_one_or_none()
    if not profile:
        raise ValueError("Сначала заполните профиль контент-маркетинга")

    platform_name = "Instagram" if platform == "instagram" else "Telegram"

    # Create plan record
    plan = ContentPlan(
        user_id=user_id,
        title=f"Контент-план {platform_name} на {period_days} дней",
        platform=platform,
        period_days=period_days,
        status="generating",
    )
    db.add(plan)
    await db.flush()

    await _fill_plan(plan, profile, platform_name, db)
    await db.refresh(plan)
    return plan


async def fill_plan_background(plan_id: int) -> None:
    """Background-task entry point. Opens its own DB session and fills an existing plan row."""
    from app.database import async_session  # local import to avoid cycles at module load

    async with async_session() as db:
        result = await db.execute(
            select(ContentPlan).where(ContentPlan.id == plan_id)
        )
        plan = result.scalar_one_or_none()
        if not plan:
            logger.error("fill_plan_background: plan #%d not found", plan_id)
            return

        profile_res = await db.execute(
            select(ContentProfile).where(ContentProfile.user_id == plan.user_id)
        )
        profile = profile_res.scalar_one_or_none()
        if not profile:
            plan.status = "error"
            plan.error_message = "Профиль контент-маркетинга не найден"
            await db.commit()
            return

        platform_name = "Instagram" if plan.platform == "instagram" else "Telegram"
        await _fill_plan(plan, profile, platform_name, db)


async def _fill_plan(
    plan: ContentPlan,
    profile: ContentProfile,
    platform_name: str,
    db: AsyncSession,
) -> None:
    """Execute steps 1-5 for an already-created plan row and commit the result."""
    platform = plan.platform
    period_days = plan.period_days
    try:
        # ── Step 1: Narrative core (cached per profile) ────
        core = await ensure_narrative_core(profile, db)
        logger.info(
            "Narrative core for profile %d: cache_hit=%s",
            profile.id,
            core["cache_hit"],
        )
        narrative_text = core["narrative_core_text"]
        strategy = core["strategy"] or {}

        # ── Step 2: Deterministic skeleton (0 tokens) ──────
        meepo_link = (profile.meepo_bot_deeplink or "").strip() or None
        slots: list[Slot] = build_skeleton(
            period_days=period_days,
            platform=platform,
            niche=profile.niche,
            meepo_deeplink=meepo_link,
            include_posts=False,  # v1: только сторис + рилс
        )
        skeleton_table = skeleton_to_prompt_table(slots)
        logger.info(
            "Skeleton for plan #%d: %d slots (stories=%d reels=%d meepo_cta=%d)",
            plan.id,
            len(slots),
            sum(1 for s in slots if s.post_type == "сторис"),
            sum(1 for s in slots if s.post_type == "рилс"),
            sum(1 for s in slots if s.is_meepo_cta),
        )

        # ── Step 3: Competitor data (cheap context, optional) ──
        competitor_data = await _gather_competitor_data(profile, db)

        # ── Step 4: One batch GPT call (cheap model) ───────
        posts_prompt = _build_batch_posts_prompt(
            profile=profile,
            platform_name=platform_name,
            narrative_text=narrative_text,
            strategy=strategy,
            skeleton_table=skeleton_table,
            competitor_data=competitor_data,
            meepo_link=meepo_link,
        )

        posts_raw = await _call_gpt(
            [{"role": "user", "content": posts_prompt}],
            temperature=0.8,
            model=_MODEL_POSTS,
        )

        # Parse posts JSON (strip markdown fence if present)
        posts_text = posts_raw.strip()
        if "```" in posts_text:
            posts_text = posts_text.split("```")[1]
            if posts_text.startswith("json"):
                posts_text = posts_text[4:]
            posts_text = posts_text.strip()

        try:
            posts_list = json.loads(posts_text)
        except json.JSONDecodeError:
            logger.error("Failed to parse posts JSON. Raw head: %s", posts_text[:400])
            raise

        # Index GPT output by (day, type) so we can align it with the authoritative skeleton.
        by_key: dict[tuple[int, str], dict] = {}
        for raw in posts_list:
            try:
                day = int(raw.get("day") or raw.get("day_number") or 0)
            except (TypeError, ValueError):
                day = 0
            ptype = (raw.get("type") or raw.get("post_type") or "").strip()
            if day and ptype:
                by_key[(day, ptype)] = raw

        # ── Step 5: Persist items strictly following the skeleton ──
        created = 0
        for s in slots:
            raw = by_key.get((s.day, s.post_type), {})
            text = (raw.get("text") or "").strip()
            if not text:
                # Safety net: never persist an empty post; leave a minimal placeholder
                # so the slot is still visible to the user.
                text = f"[{s.post_type} день {s.day}] — контент не сгенерирован, отредактируйте вручную."
            topic = (raw.get("topic") or "")[:255] or f"{s.post_type} день {s.day}"
            hashtags = raw.get("hashtags") if platform == "instagram" else None
            script = None
            if s.post_type in ("рилс", "сторис"):
                script = raw.get("script") or None

            item = ContentPlanItem(
                plan_id=plan.id,
                day_number=s.day,
                post_type=s.post_type,
                topic=topic,
                text=text,
                hashtags=hashtags,
                best_time=raw.get("time") or s.best_time,
                script=script,
                hunt_stage=s.hunt_stage,
                is_meepo_cta=s.is_meepo_cta,
            )
            db.add(item)
            created += 1

        plan.status = "ready"
        await db.commit()
        logger.info("Content plan #%d generated: %d items", plan.id, created)

    except Exception as e:
        logger.error("Content plan generation failed: %s", e, exc_info=True)
        plan.status = "error"
        plan.error_message = (str(e) or e.__class__.__name__)[:500]
        await db.commit()


async def analyze_profile_from_posts(posts_texts: list[str]) -> dict:
    """Analyze user's own social media posts to auto-detect niche, audience, tone, topics.

    Returns dict with keys: niche, target_audience, tone, topics (list).
    """
    if not posts_texts:
        raise ValueError("Нет постов для анализа")

    sample = "\n---\n".join(posts_texts[:20])

    prompt = f"""Ты — маркетолог-аналитик. Проанализируй посты из социальной сети одного автора и определи его профиль.

## Посты автора
{sample}

## Задача
На основе анализа постов определи:
1. **Ниша** — в какой нише работает автор (1-3 слова, например: "wellness и БАДы", "фитнес", "косметология")
2. **Целевая аудитория** — кто читает эти посты: пол, примерный возраст, интересы, боли, мотивация (2-4 предложения)
3. **Тон** — какой тон использует автор. Выбери ОДИН из: friendly, professional, expert, casual, motivational
4. **Темы** — основные темы постов (3-8 тем через запятую)

Ответь СТРОГО в формате JSON:
{{
  "niche": "...",
  "target_audience": "...",
  "tone": "friendly|professional|expert|casual|motivational",
  "topics": ["тема1", "тема2", ...]
}}"""

    raw = await _call_gpt(
        [{"role": "user", "content": prompt}],
        temperature=0.3,
    )

    text = raw.strip()
    if "```" in text:
        text = text.split("```")[1]
        if text.startswith("json"):
            text = text[4:]
        text = text.strip()

    result = json.loads(text)

    # Validate tone
    valid_tones = {"friendly", "professional", "expert", "casual", "motivational"}
    if result.get("tone") not in valid_tones:
        result["tone"] = "friendly"

    return result
